### ISSUE TITLE
Why all these global variables?

### ISSUE THREAD

**Issue by Luux** [jerrymarshall2004/BeatSaberPythonMapper#1]
Hi,
making all the variables global results in the classes not following object-oriented principles. I think you should just ommit the globals as this can have nasty side effects.

For example, this code snipped follows your proposed style (see example.py):

```
normalStandard = level

#Define the attributes of normalStandard (Not required, default values are provided)
normalStandard.characteristicName = "Standard"
normalStandard.difficulty = "Normal"
normalStandard.difficultyRank = 3
normalStandard.noteJumpMovementSpeed = 12
normalStandard.noteJumpStartBeatOffset = 0
normalStandard.editorOffset = 0
normalStandard.editorOldOffset = 0
normalStandard.warnings = "Don't Break Ur Arms Lol"
normalStandard.information = "Mapped With Beat Saber Python Mapper"
normalStandard.suggestions = "Technicolor, Chroma"
normalStandard.requirements = ""

level2 = level
level2.characteristicName = "abc"
level2.difficultyRank = 3
level2.warnings = "Hi"

print(level.warnings)
print(level2.warnings)
```

One would expect that this results in
```
Don't Break Ur Arms Lol
Hi
```

However, this is not the case. Instead the example above results in
```
Hi
Hi
```

The same happens to all other attributes. This is because you define object attributes, but then you make them global. This is easily fixable. Instead of something like
```
global characteristicName

class level:
    def __init__(self):
        global characteristicName
        self.characteristicName = characteristicName
```

just use

```
class level:
    def __init__(self):
        self.characteristicName = characteristicName
```

When working with the classes, switch from `normalStandard = level` to `normalStandard = level()`. The first one is the python class itself you assign to normalStandard, the second one is an instance. Usually you want to work with instances :) This is also less boilerplate-y as you only need to define variables once instead of 3 times.

**Comment by jerrymarshall2004** [comment]
Okay thank you, this was my first time using classes and such. I can make
you a collaborator on the project if you’d like to help me with that
